Repository graknlabs/benchmark, pull requests merged in 2019-08, with the labels that each got.

#295 Refactors src/utils.ts
  service/web-server/src/config.ts
  service/web-server/src/controllers/auth/index.ts
  service/web-server/src/controllers/auth/utils.ts
  service/web-server/src/routes/auth.ts
  service/web-server/src/server.ts
  service/web-server/src/utils.ts
  service/web-server/test/integration/server.test.js
Labels: bug, refactor

#297 Restructures the files and directories of Web Server
  service/web-server/src/ExecutionsController.js
  service/web-server/src/SpansController.js
  service/web-server/src/auth/controller.ts
  service/web-server/src/auth/githubClient.ts
  service/web-server/src/auth/routes.ts
  service/web-server/src/controllers/utils.ts
  service/web-server/src/execution/controller.ts
  service/web-server/src/execution/middlewares.ts
  service/web-server/src/execution/routes.ts
  service/web-server/src/execution/types.ts
  service/web-server/src/execution/vmClient/index.ts
  service/web-server/src/execution/vmClient/scripts/downloadLogs.sh
  service/web-server/src/execution/vmClient/scripts/runExecute.sh
  service/web-server/src/help
  service/web-server/src/server.ts
  service/web-server/src/span/controller.ts
  service/web-server/src/span/routes.ts
  service/web-server/src/utils.ts
Labels: refactor

#301 Query Generator v1
  .circleci/config.yml
  profiler/test-integration/DataImportIT.java
  querygen/BUILD
  querygen/src/BUILD
  querygen/src/Pair.java
  querygen/src/QueryBuilder.java
  querygen/src/QueryGenerator.java
  querygen/src/SchemaWalker.java
  querygen/test-integration/BUILD
  querygen/test-integration/QueryGeneratorIT.java
  querygen/test-integration/SchemaWalkerIT.java
  querygen/test-integration/conf/BUILD
  querygen/test-integration/conf/cassandra-embedded.yaml
  querygen/test-integration/conf/grakn.properties
  querygen/test-integration/resources/BUILD
  querygen/test-integration/resources/logback.xml
  querygen/test-integration/resources/schema.gql
Labels: feature

#299 Change benchmark Keyspace names to be CQL compatible
  service/executor/execute.sh
Labels: bug

#304 Update License header to 2019
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/dependencies.yaml
  dependencies/maven/update.sh
  deployment.properties
  metric/logback.xml
  profiler/benchmark
  profiler/setup.sh
  profiler/src/logback.xml
  querygen/test-integration/conf/grakn.properties
  report/formatter/logback.xml
  report/producer/logback.xml
Labels: refactor

#303 Query generator v2: Multi-hop queries and attribute-attribute comparisons
  querygen/README.md
  querygen/src/QueryBuilder.java
  querygen/src/QueryGenerator.java
  querygen/test-integration/QueryGeneratorIT.java
Labels: feature

#305 Query generator v3 - Query Metrics
  dependencies/graknlabs/dependencies.bzl
  querygen/src/Pair.java
  querygen/src/QueryBuilder.java
  querygen/src/QueryGenerator.java
  querygen/src/SchemaWalker.java
  querygen/src/Vectoriser.java
  querygen/test-integration/BUILD
  querygen/test-integration/QueryGeneratorIT.java
  querygen/test-integration/SchemaWalkerIT.java
  querygen/test/BUILD
  querygen/test/VectoriserTest.java
Labels: feature

#306 Add Joshua, Soroush, and Marco as the code owners
  .github/CODEOWNERS
Labels: build
