Repository graknlabs/benchmark, pull requests merged in 2019-05, with the labels that each got.

#186 Fixes a bug with the selection of the sort type on the Executions page
  service/dashboard/src/views/executions/Executions.vue
Labels: bug

#187 refactors Inspect and TabularView + makes ExecutionCard reusable
  service/dashboard/src/assets/css/_overrides.scss
  service/dashboard/src/util/filters.js
  service/dashboard/src/views/executions/ExecutionCard.vue
  service/dashboard/src/views/executions/Executions.vue
  service/dashboard/src/views/inspect/Inspect.vue
  service/dashboard/src/views/inspect/TabularView/TabularView.vue
Labels: refactor

#188 Refactors GraphTab
  service/dashboard/src/views/inspect/TabularView/GraphTab.vue
  service/dashboard/src/views/inspect/TabularView/TabularView.vue
  service/dashboard/src/views/overview/ChartCommits.vue
Labels: refactor

#190 Post-processes fetched data and refactors accordingly
  service/dashboard/.eslintrc.js
  service/dashboard/package.json
  service/dashboard/src/assets/css/_base.scss
  service/dashboard/src/assets/css/_overrides.scss
  service/dashboard/src/components/ScaleSelector.vue
  service/dashboard/src/components/Selector.vue
  service/dashboard/src/util/ExecutionDataModifiers.js
  service/dashboard/src/util/filters.js
  service/dashboard/src/views/executions/ExecutionCard.vue
  service/dashboard/src/views/executions/Executions.vue
  service/dashboard/src/views/inspect/Inspect.vue
  service/dashboard/src/views/inspect/TabularView/GraphTab.vue
  service/dashboard/src/views/inspect/TabularView/Queries.vue
  service/dashboard/src/views/inspect/TabularView/QueriesTable.vue
  service/dashboard/src/views/inspect/TabularView/QueryCard.vue
  service/dashboard/src/views/inspect/TabularView/TabularView.vue
  service/dashboard/src/views/overview/ChartCommits.vue
  service/dashboard/src/views/overview/QueriesUtil.js
  service/dashboard/src/views/overview/index.vue
  service/dashboard/yarn.lock
Labels: don't merge, refactor

#191 Refactors StepLine (query child steps)
  service/dashboard/src/assets/css/_base.scss
  service/dashboard/src/assets/css/_overrides.scss
  service/dashboard/src/assets/css/_variables.scss
  service/dashboard/src/components/Selector.vue
  service/dashboard/src/components/TheSideNav.vue
  service/dashboard/src/util/ExecutionDataFormatters.js
  service/dashboard/src/views/executions/ExecutionCard.vue
  service/dashboard/src/views/executions/Executions.vue
  service/dashboard/src/views/inspect/Inspect.vue
  service/dashboard/src/views/inspect/TabularView/GraphTab.vue
  service/dashboard/src/views/inspect/TabularView/Queries.vue
  service/dashboard/src/views/inspect/TabularView/QueryCard.vue
  service/dashboard/src/views/inspect/TabularView/QueryLine.vue
  service/dashboard/src/views/inspect/TabularView/StepLine.vue
  service/dashboard/src/views/overview/ChartCommits.vue
  service/dashboard/src/views/overview/QueriesUtil.js
  service/dashboard/src/views/overview/index.vue
Labels: refactor

#193 set initial behaviour for sorting executions
  service/dashboard/src/views/executions/Executions.vue
Labels: bug

#195 Benchmark Profiler - Static Graph Loading
  .circleci/config.yml
  common/configuration/BUILD
  common/configuration/BenchmarkConfiguration.java
  common/configuration/parse/BenchmarkArguments.java
  common/configuration/parse/BenchmarkConfigurationFile.java
  common/configuration/test/BUILD
  common/configuration/test/ConfigurationTest.java
  common/configuration/test/resources/BUILD
  common/configuration/test/resources/logback.xml
  common/configuration/test/resources/web_content/queries_read.yml
  common/configuration/test/resources/web_content/web_content_config_data_gen.yml
  common/configuration/test/resources/web_content/web_content_config_data_import.yml
  common/configuration/test/resources/web_content/web_content_data.gql
  common/configuration/test/resources/web_content/web_content_schema.gql
  profiler/src/GraknBenchmark.java
  profiler/src/QueryProfiler.java
  profiler/src/ThreadedProfiler.java
  profiler/src/util/ConcurrentDataLoader.java
  profiler/test-integration/BUILD
  profiler/test-integration/DataImportIT.java
  profiler/test-integration/ProfilerBootupIT.java
  profiler/test-integration/resources/BUILD
  profiler/test-integration/resources/logback.xml
  profiler/test-integration/resources/web_content/queries_read.yml
  profiler/test-integration/resources/web_content/web_content_config_data_gen.yml
  profiler/test-integration/resources/web_content/web_content_config_data_import.yml
  profiler/test-integration/resources/web_content/web_content_data.gql
  profiler/test-integration/resources/web_content/web_content_schema.gql
  profiler/test/BUILD
Labels: feature

#197 Differentiate chart nodes with high standard deviation in ChartCommits
  service/dashboard/src/views/overview/ChartCommits.vue
Labels: feature

#204 fix a bug with deletable/stoppable executions
  service/dashboard/src/views/executions/ExecutionCard.vue
Labels: bug

#205 Load preSelectedQuery on the inspect page when available within query params
  service/dashboard/src/views/inspect/Inspect.vue
  service/dashboard/src/views/inspect/TabularView/GraphTab.vue
  service/dashboard/src/views/inspect/TabularView/Queries.vue
  service/dashboard/src/views/inspect/TabularView/QueryCard.vue
  service/dashboard/src/views/inspect/TabularView/TabularView.vue
Labels: bug

#208 Fixes gcloud copy undefined vmname
  service/dashboard/src/views/executions/Executions.vue
Labels: bug

#213 Re-enable complex queries
  .bazelrc
  .github/PULL_REQUEST_TEMPLATE.md
  common/configuration/scenario/complex/config_read.yml
  common/configuration/scenario/complex/queries_complex_read.yml
  dependencies/graknlabs/dependencies.bzl
  profiler/src/BUILD
  profiler/src/GraknBenchmark.java
  profiler/src/QueryProfiler.java
  profiler/src/ThreadedProfiler.java
  profiler/src/util/TracingGraknClient.java
Labels: refactor
