Repository graknlabs/benchmark, pull requests merged in 2019-09, with the labels that each got.

#308 Fix dependencies
  dependencies/graknlabs/dependencies.bzl
Labels: bug

#309 Fixes various bugs in web server and dashboard
  service/dashboard/src/util/ExecutionDataFormatters.js
  service/dashboard/src/views/Inspect/components/QueryCard/index.vue
  service/dashboard/src/views/Inspect/components/StepLine/index.vue
  service/dashboard/src/views/Inspect/index.vue
  service/dashboard/src/views/overview/components/ChartCommits/index.vue
  service/delete_instance.sh
  service/deploy_web_server.sh
  service/executor/execute.sh
  service/launch_executor_server.sh
  service/launch_service.sh
  service/package-lock.json
  service/web-server/src/config.ts
  service/web-server/src/execution/controller.ts
  service/web-server/src/execution/vmClient/index.ts
  service/web-server/src/execution/vmClient/scripts/downloadLogs.sh
  service/web-server/src/server.ts
Labels: bug

#312 Fix Reasoner Benchmark Queries
  common/configuration/scenario/reasoning/queries_read.yml
Labels: bug

#313 Disable cassandra caches and JVM JITs
  service/web-server/resources/execute.sh
Labels: refactor

#314 Remove http:// from zipkin launch and Open Zipkin port
  service/web-server/resources/execute.sh
  service/web-server/src/execution/vmClient/index.ts
Labels: bug

#315 Fix grakn.properties Permissions
  service/web-server/resources/execute.sh
Labels: bug

#311 Updates instructions on starting the web-server
  service/web-server/README.md
Labels: build

#316 GCP Disk Autodelete and Bazel clean before grakn Build in execute.sh
  service/web-server/resources/execute.sh
  service/web-server/src/execution/vmClient/index.ts
Labels: bug

#317 Reduce benchmark repetitions
  common/configuration/scenario/attribute/attribute_read_config.yml
  common/configuration/scenario/biochemical_network/biochemical_config_read.yml
  common/configuration/scenario/complex/config_read.yml
  common/configuration/scenario/complex/config_write.yml
  common/configuration/scenario/road_network/road_config_read.yml
  common/configuration/scenario/schema/data_definition_config.yml
  service/web-server/resources/execute.sh
Labels: refactor

#319 Fix test and reduce QueryGenerator nondeterminism
  querygen/src/SchemaWalker.java
  querygen/test-integration/BUILD
  querygen/test-integration/QueryGeneratorIT.java
  querygen/test-integration/conf/grakn.properties
Labels: bug

#320 Prepare for bazel upgrade
  .bazelrc
Labels: bug, build

#318 Adds Long type support to GraphQL
  service/web-server/src/graphqlTypes.ts
  service/web-server/src/span/controller.ts
Labels: bug

#298 Web Server: Final refactoring touches
  service/web-server/src/auth/controller.ts
  service/web-server/src/auth/githubClient.ts
  service/web-server/src/auth/middlewares.ts
  service/web-server/src/auth/routes.ts
  service/web-server/src/execution/controller.ts
  service/web-server/src/execution/middlewares.ts
  service/web-server/src/execution/routes.ts
  service/web-server/src/execution/vmClient/index.ts
  service/web-server/src/server.ts
  service/web-server/src/span/controller.ts
  service/web-server/src/span/routes.ts
  service/web-server/src/types.ts
Labels: refactor
