Repository graknlabs/benchmark, pull requests merged in 2019-04, with the labels that each got.

#163 New Readme's
  README.md
  common/configuration/scenario/road_network/road_config_read.yml
  generator/README.md
  profiler/README.md
  report/README.md
  report/producer/gcp_client_server.sh
Labels: refactor

#165 Bump Graql and Client-Java versions
  common/configuration/scenario/road_network/queries_read.yml
  dependencies/graknlabs/dependencies.bzl
  profiler/src/util/ElasticSearchManager.java
  report/producer/BUILD
  report/producer/ReportProducer.java
Labels: refactor

#173 Add to write queries with attributes, gather all id's to delete and …
  common/configuration/scenario/complex/queries_complex_write.yml
  common/configuration/scenario/road_network/queries_write.yml
  profiler/src/QueryProfiler.java
  service/executor/execute.sh
  service/web-server/src/Utils.js
Labels: bug

#174 Revert delete concept changes, add a new query
  common/configuration/scenario/biochemical_network/queries_read.yml
  common/configuration/scenario/complex/queries_complex_read.yml
  profiler/src/QueryProfiler.java
  service/executor/execute.sh
Labels: bug

#177 Delete Inserted IDs in one Tx
  BUILD
  profiler/src/QueryProfiler.java
Labels: refactor

#179 Track time spent on Generation/Querying/Other and bump deps
  WORKSPACE
  common/analysis/test/InsertQueryAnalyserTest.java
  common/timer/BUILD
  common/timer/BenchmarkingTimer.java
  dependencies/graknlabs/dependencies.bzl
  generator/BUILD
  generator/DataGenerator.java
  generator/query/AttributeGenerator.java
  generator/query/RelationGenerator.java
  profiler/src/BUILD
  profiler/src/GraknBenchmark.java
  profiler/src/QueryProfiler.java
  profiler/src/ThreadedProfiler.java
  report/producer/BUILD
  report/producer/ReportProducer.java
Labels: feature

#184 Adds functionality for sorting executions by column
  service/dashboard/src/assets/css/_overrides.scss
  service/dashboard/src/components/Selector.vue
  service/dashboard/src/components/SelectorScale.vue
  service/dashboard/src/views/executions/ExecutionCard.vue
  service/dashboard/src/views/executions/Executions.vue
  service/dashboard/src/views/overview/ChartCommits.vue
Labels: feature
