Repository graknlabs/benchmark, pull requests merged in 2019-07, with the labels that each got.

#246 Simplifies the dashboard's URL
  service/dashboard/package.json
  service/deploy_web_server.sh
  service/executor/execute.sh
  service/launch_service.sh
  service/web-server/src/config.js
  service/web-server/src/server.js
Labels: refactor

#247 Schema profiler scenarios and scenario cleanup
  BUILD
  common/configuration/scenario/biochemical_network/biochemical_config_read.yml
  common/configuration/scenario/complex/queries_complex_read.yml
  common/configuration/scenario/financial_transactions/financial.gql
  common/configuration/scenario/financial_transactions/financial_config_read.yml
  common/configuration/scenario/financial_transactions/queries_read.yml
  common/configuration/scenario/schema/data_definition_config.yml
  common/configuration/scenario/schema/data_definition_schema.gql
  common/configuration/scenario/schema/queries.yml
  common/configuration/scenario/social_network/queries_read.yml
  common/configuration/scenario/social_network/social_network.gql
  common/configuration/scenario/social_network/social_network_config_read.yml
  common/configuration/scenario/taxfix/config.yml
  common/configuration/scenario/taxfix/config_small.yml
  common/configuration/scenario/taxfix/queries.yml
  common/configuration/scenario/taxfix/queries_all.yml
  common/configuration/scenario/taxfix/queries_small.yml
  common/configuration/scenario/taxfix/taxfix_schema.gql
  generator/definition/BiochemicalNetworkDefinition.java
  generator/definition/DefinitionFactory.java
  generator/definition/SocialNetworkDefinition.java
  service/executor/execute.sh
Labels: don't merge, feature, refactor

#250 Fix schema profiling scenario
  BUILD
  common/configuration/scenario/attribute/attributes_read_config.yml
  common/configuration/scenario/attribute/attributes_schema.gql
  common/configuration/scenario/attribute/queries_read.yml
  common/configuration/scenario/complex/queries_complex_write.yml
  common/configuration/scenario/schema/data_definition_config.yml
  common/configuration/scenario/schema/data_definition_schema.gql
  common/configuration/scenario/schema/queries.yml
  generator/definition/AttributeDefinition.java
  generator/definition/BiochemicalNetworkDefinition.java
  generator/definition/DefinitionFactory.java
  generator/definition/FinancialTransactionsDefinition.java
  generator/provider/value/ScalingGaussianIntegerProvider.java
  profiler/src/QueryProfiler.java
  service/executor/execute.sh
Labels: bug

#254 Profiler scenario expansion 2 - Attribute operations
  BUILD
  common/configuration/scenario/attribute/attribute_read_config.yml
  common/configuration/scenario/attribute/attribute_schema.gql
  common/configuration/scenario/attribute/queries_read.yml
  common/configuration/scenario/complex/config_write.yml
  common/configuration/scenario/complex/queries_complex_read.yml
  common/configuration/scenario/complex/schema.gql
  common/configuration/scenario/road_network/queries_read.yml
  common/configuration/scenario/road_network/road_network.gql
  generator/definition/AttributeDefinition.java
  generator/definition/DefinitionFactory.java
  generator/definition/RoadNetworkDefinition.java
  generator/provider/value/ScalingGaussianDoubleProvider.java
  generator/query/AttributeGenerator.java
  service/executor/execute.sh
Labels: feature

#257 Remove attribute scenario syntax error
  common/configuration/scenario/attribute/queries_read.yml
Labels: bug

#259 Updates the histogram of QueryCard upon changing the scale
  service/dashboard/src/views/Inspect/components/QueryCard/index.vue
  service/web-server/src/config.js
Labels: bug

#264 Rename scenarios and update tags
  common/configuration/scenario/biochemical_network/biochemical_config_read.yml
  common/configuration/scenario/reasoning/config_read.yml
  common/configuration/scenario/rule_scaling/config_read.yml
  profiler/src/QueryProfiler.java
Labels: refactor

#265 Aesthetic updates
  profiler/src/QueryProfiler.java
Labels: refactor

#267 Update README.md
  service/web-server/README.md
Labels: bug

#268 1 - Brings back the v-loading directive
  service/dashboard/src/assets/css/elements/_index.scss
  service/dashboard/src/assets/css/elements/_spinner.scss
  service/dashboard/src/assets/css/global.scss
  service/dashboard/src/main.js
  service/dashboard/src/plugins/vue-loading/index.js
  service/dashboard/src/plugins/vue-loading/loading.vue
  service/dashboard/src/plugins/vue-loading/util/after-leave.js
  service/dashboard/src/plugins/vue-loading/util/dom.js
  service/dashboard/src/views/Executions/index.vue
  service/dashboard/src/views/Inspect/components/QueryCard/index.vue
  service/dashboard/src/views/overview/components/ChartCommits/index.vue
Labels: refactor

#269 Improves Selector, ExecutionsPage
  service/dashboard/src/components/Selector.vue
  service/dashboard/src/views/Executions/components/ExecutionCard/index.vue
  service/dashboard/src/views/Executions/index.vue
  service/dashboard/src/views/Inspect/components/GraphTab/index.vue
  service/dashboard/src/views/Inspect/components/QueryCard/index.vue
  service/dashboard/src/views/Inspect/index.vue
  service/dashboard/src/views/overview/components/ChartCommits/index.vue
Labels: refactor

#271 General refactoring of dashboard components
  service/dashboard/.eslintrc.js
  service/dashboard/src/util/math.js
  service/dashboard/src/views/Inspect/components/GraphTab/index.vue
  service/dashboard/src/views/Inspect/components/GraphTabs/index.vue
  service/dashboard/src/views/Inspect/components/GroupLine/index.vue
  service/dashboard/src/views/Inspect/components/QueryCard/index.vue
  service/dashboard/src/views/Inspect/components/QueryCard/util.js
  service/dashboard/src/views/Inspect/components/QueryCards/index.vue
  service/dashboard/src/views/Inspect/components/StepLine/index.vue
  service/dashboard/src/views/Inspect/index.vue
  service/dashboard/src/views/overview/components/ChartCommits/index.vue
  service/dashboard/src/views/overview/components/ChartCommits/util.js
  service/dashboard/src/views/overview/index.vue
Labels: refactor

#276 (Re)implement ExecutionController, VmController and ExecutionRoutes
  service/web-server/.eslintrc.js
  service/web-server/.gitignore
  service/web-server/package.json
  service/web-server/resources/execute.sh
  service/web-server/src/ExecutionsController.js
  service/web-server/src/Utils.js
  service/web-server/src/config.js
  service/web-server/src/config.ts
  service/web-server/src/controllers/execution/index.ts
  service/web-server/src/controllers/span.js
  service/web-server/src/controllers/vm/index.ts
  service/web-server/src/controllers/vm/scripts/downloadLogs.sh
  service/web-server/src/controllers/vm/scripts/runExecute.sh
  service/web-server/src/help
  service/web-server/src/routes/execution.ts
  service/web-server/src/routes/span.js
  service/web-server/src/server.js
  service/web-server/src/server.ts
  service/web-server/src/types.ts
  service/web-server/src/utils.ts
  service/web-server/test/e2e/queryExecutions.test.js
  service/web-server/test/esdriver.test.js
  service/web-server/test/integration/server.test.js
  service/web-server/test/test_script.sh
  service/web-server/tsconfig.json
  service/web-server/yarn.lock
Labels: refactor

#280 Report generator - log queries
  common/configuration/scenario/road_network/road_config_read_c4.yml
  common/configuration/scenario/road_network/road_config_read_c8.yml
  report/producer/AnswerAnalysis.java
  report/producer/QueriesExecutor.java
  report/producer/ReportProducer.java
Labels: refactor

#283 Change from IP to internal google name
  service/executor/execute.sh
Labels: bug, refactor

#286 Refactors the span controller and routes
  service/web-server/src/SpansController.js
  service/web-server/src/config.ts
  service/web-server/src/controllers/execution/index.ts
  service/web-server/src/controllers/span.js
  service/web-server/src/controllers/span/index.ts
  service/web-server/src/controllers/utils.ts
  service/web-server/src/routes/span.js
  service/web-server/src/routes/span.ts
  service/web-server/src/server.ts
Labels: refactor

#288 Rectify Execution and VM controllers
  service/web-server/src/controllers/execution/index.ts
  service/web-server/src/controllers/vm/index.ts
Labels: bug, refactor

#292 Refactor server.ts
  service/web-server/.eslintrc.js
  service/web-server/package.json
  service/web-server/src/config.ts
  service/web-server/src/controllers/auth/index.ts
  service/web-server/src/controllers/execution/index.ts
  service/web-server/src/controllers/span/index.ts
  service/web-server/src/controllers/vm/index.ts
  service/web-server/src/routes/auth.ts
  service/web-server/src/routes/execution.ts
  service/web-server/src/routes/span.ts
  service/web-server/src/server.ts
  service/web-server/src/utils.ts
  service/web-server/tsconfig.json
  service/web-server/yarn.lock
Labels: refactor
