Repository graknlabs/benchmark, pull requests merged in 2019-06, with the labels that each got.

#218 Add rule scaling test
  BUILD
  common/configuration/scenario/rule_scaling/config_read.yml
  common/configuration/scenario/rule_scaling/queries_read.yml
  common/configuration/scenario/rule_scaling/rule_scaling_data.gql
  common/configuration/scenario/rule_scaling/rule_scaling_schema.gql
  service/executor/execute.sh
Labels: feature

#220 Refactor
  .circleci/config.yml
  common/configuration/scenario/rule_scaling/rule_scaling_schema.gql
  generator/definition/DefinitionFactory.java
  generator/storage/IgniteConceptStorage.java
  generator/test-integration/BUILD
  generator/test-integration/util/KeyspaceSchemaLabelsIT.java
  generator/test/storage/IgniteConceptStorageTest.java
  generator/util/KeyspaceSchemaLabels.java
  generator/util/SchemaManager.java
  profiler/src/BUILD
  profiler/src/GraknBenchmark.java
  profiler/src/logback.xml
  profiler/src/usecase/LoadSchema.java
  profiler/src/usecase/LoadSchemaGenerateData.java
  profiler/src/usecase/LoadSchemaLoadData.java
  profiler/src/usecase/ProfileExisting.java
  profiler/src/usecase/UseCase.java
  profiler/src/usecase/UseCaseFactory.java
  profiler/src/util/SchemaManager.java
  profiler/test-integration/DataImportIT.java
  profiler/test-integration/ProfilerBootupIT.java
  report/producer/ReportProducer.java
  service/executor/execute.sh
Labels: refactor

#222 Add extra query with insertions to reasoning benchmark
  common/configuration/scenario/reasoning/queries_read.yml
Labels: feature

#212 Makes ExecutionCard clickable
  service/dashboard/src/views/executions/ExecutionCard.vue
  service/dashboard/src/views/executions/Executions.vue
Labels: feature

#223 Updates executions list on action
  service/dashboard/src/views/executions/ExecutionCard.vue
  service/dashboard/src/views/executions/Executions.vue
Labels: bug

#226 Groups consequent steps
  service/dashboard/src/components/TheSideNav.vue
  service/dashboard/src/router.js
  service/dashboard/src/views/inspect/TabularView/GroupLine.vue
  service/dashboard/src/views/inspect/TabularView/QueryCard.vue
  service/dashboard/src/views/inspect/TabularView/StepLine.vue
Labels: feature

#229 Improves UI/UX of the Inspect page
  service/dashboard/src/assets/css/_overrides.scss
  service/dashboard/src/util/ExecutionDataFormatters.js
  service/dashboard/src/util/ExecutionDataModifiers.js
  service/dashboard/src/util/filters.js
  service/dashboard/src/views/inspect/Inspect.vue
  service/dashboard/src/views/inspect/TabularView/GraphTab.vue
  service/dashboard/src/views/inspect/TabularView/GroupLine.vue
  service/dashboard/src/views/inspect/TabularView/QueryCard.vue
  service/dashboard/src/views/inspect/TabularView/StepLine.vue
Labels: feature

#230 Update reasoning example to cater for attribute materialisation
  common/configuration/scenario/reasoning/queries_read.yml
  common/configuration/scenario/reasoning/transitivity_data.gql
  common/configuration/scenario/reasoning/transitivity_schema.gql
Labels: feature

#233 Handles get requests with vue router history mode
  .gitignore
  service/web-server/package-lock.json
  service/web-server/package.json
  service/web-server/src/server.js
  service/web-server/yarn.lock
Labels: bug

#234 set limit of 1000 for fetching executions
  service/dashboard/src/views/executions/Executions.vue
Labels: bug

#236 Includes histogram and other stats in QueryCard
  service/dashboard/src/util/ExecutionDataFormatters.js
  service/dashboard/src/views/inspect/Inspect.vue
  service/dashboard/src/views/inspect/TabularView/GraphTab.vue
  service/dashboard/src/views/inspect/TabularView/GroupLine.vue
  service/dashboard/src/views/inspect/TabularView/QueryCard.vue
  service/dashboard/src/views/inspect/TabularView/StepLine.vue
  service/dashboard/src/views/inspect/TabularView/utils.js
Labels: feature, refactor

#237 Re-arranges the directory structure
  service/dashboard/src/router.js
  service/dashboard/src/views/Executions/components/ExecutionCard.vue
  service/dashboard/src/views/Executions/index.vue
  service/dashboard/src/views/Inspect/components/GraphTab.vue
  service/dashboard/src/views/Inspect/components/GroupLine.vue
  service/dashboard/src/views/Inspect/components/Queries.vue
  service/dashboard/src/views/Inspect/components/QueryCard/index.vue
  service/dashboard/src/views/Inspect/components/QueryCard/util.js
  service/dashboard/src/views/Inspect/components/StepLine.vue
  service/dashboard/src/views/Inspect/components/TabularView.vue
  service/dashboard/src/views/Inspect/index.vue
  service/dashboard/src/views/overview/components/ChartCommits/index.vue
  service/dashboard/src/views/overview/components/ChartCommits/util.js
  service/dashboard/src/views/overview/index.vue
Labels: refactor

#238 Move from `id` to `key` in Data Generator and fix Nondeterminism
  common/configuration/scenario/biochemical_network/biochemical_config_read.yml
  common/configuration/scenario/biochemical_network/biochemical_network.gql
  common/configuration/scenario/complex/config_read.yml
  common/configuration/scenario/complex/schema.gql
  common/configuration/scenario/financial_transactions/financial.gql
  common/configuration/scenario/financial_transactions/financial_config_read.yml
  common/configuration/scenario/road_network/queries_write.yml
  common/configuration/scenario/road_network/road_config_read.yml
  common/configuration/scenario/road_network/road_config_read_c4.yml
  common/configuration/scenario/road_network/road_config_read_c8.yml
  common/configuration/scenario/road_network/road_config_write_c4.yml
  common/configuration/scenario/road_network/road_config_write_c8.yml
  common/configuration/scenario/road_network/road_network.gql
  common/configuration/scenario/social_network/social_network.gql
  common/configuration/scenario/social_network/social_network_config_read.yml
  generator/DataGenerator.java
  generator/definition/BiochemicalNetworkDefinition.java
  generator/definition/FinancialTransactionsDefinition.java
  generator/definition/GenericUniformNetworkDefinition.java
  generator/definition/RoadNetworkDefinition.java
  generator/definition/SocialNetworkDefinition.java
  generator/provider/key/CentralConceptKeyProvider.java
  generator/provider/key/ConceptKeyProvider.java
  generator/provider/key/ConceptKeyStorageProvider.java
  generator/provider/key/CountingKeyProvider.java
  generator/provider/key/NotInRelationshipConceptKeyProvider.java
  generator/query/AttributeGenerator.java
  generator/query/EntityGenerator.java
  generator/query/RelationGenerator.java
  generator/storage/ConceptStorage.java
  generator/storage/IgniteConceptStorage.java
  generator/strategy/AttributeStrategy.java
  generator/strategy/EntityStrategy.java
  generator/strategy/RelationStrategy.java
  generator/strategy/RolePlayerTypeStrategy.java
  generator/strategy/TypeStrategy.java
  generator/test/provider/BUILD
  generator/test/provider/CentralConceptProviderTest.java
  generator/test/provider/ConceptKeyStorageProviderTest.java
  generator/test/provider/NotInRelationshipConceptIdProviderTest.java
  generator/test/provider/NotInRelationshipConceptKeyProviderTest.java
  generator/test/query/AttributeGeneratorTest.java
  generator/test/query/EntityGeneratorTest.java
  generator/test/query/RelationGeneratorTest.java
  generator/test/storage/IgniteConceptStorageTest.java
  profiler/src/QueryProfiler.java
Labels: refactor

#241 Fixes bug with exclusion of first rep in histogram of QueryCard
  service/dashboard/src/views/Inspect/components/QueryCard/index.vue
  service/dashboard/src/views/Inspect/components/QueryCard/util.js
Labels: bug

#243 Allows toggling query types in overview charts
  service/dashboard/src/views/overview/components/ChartCommits/index.vue
  service/dashboard/src/views/overview/components/ChartCommits/util.js
Labels: feature

#242 exclude outliers from QueryCard's histogram data
  service/dashboard/src/util/math.js
  service/dashboard/src/views/Inspect/components/QueryCard/index.vue
  service/dashboard/src/views/Inspect/components/QueryCard/util.js
Labels: feature

#244 Reduces overview chart legend/query types
  service/dashboard/src/views/overview/components/ChartCommits/index.vue
  service/dashboard/src/views/overview/components/ChartCommits/util.js
Labels: refactor

#245 Authenticates users
  service/dashboard/package.json
  service/dashboard/src/App.vue
  service/dashboard/src/assets/css/_fonts.scss
  service/dashboard/src/assets/fonts/TitilliumWeb-Light.ttf
  service/dashboard/src/main.js
  service/dashboard/src/router.js
  service/dashboard/src/util/BenchmarkClient.js
  service/dashboard/src/views/Login/index.vue
  service/dashboard/yarn.lock
  service/deploy_web_server.sh
  service/web-server/package.json
  service/web-server/src/Utils.js
  service/web-server/src/server.js
  service/web-server/yarn.lock
Labels: don't merge, feature
