Repository graknlabs/benchmark, pull requests merged in 2019-10, with the labels that each got.

#322 Fix CI by no longer depending on non-existent library
  generator/BUILD
  metric/BUILD
  profiler/src/BUILD
  querygen/src/BUILD
  report/producer/BUILD
Labels: bug, build

#323 Fix an error in 'yarn build' due to incorrect folder name
  service/dashboard/src/views/Overview/components/ChartCommits/index.vue
  service/dashboard/src/views/Overview/components/ChartCommits/style.scss
  service/dashboard/src/views/Overview/components/ChartCommits/util.js
  service/dashboard/src/views/Overview/index.vue
  service/dashboard/src/views/Overview/style.scss
Labels: bug

#324 Report formatter conditional printouts
  report/formatter/QueryDataContainer.java
Labels: refactor

#325 Synchronize changes with Grakn Core
  common/analysis/BUILD
  common/analysis/test/BUILD
  generator/BUILD
  generator/test-integration/BUILD
  generator/test/provider/BUILD
  generator/test/query/BUILD
  metric/BUILD
  profiler/src/BUILD
  profiler/test-integration/BUILD
  profiler/test-integration/ProfilerBootupIT.java
  querygen/src/BUILD
  querygen/test-integration/BUILD
  querygen/test/BUILD
  report/producer/BUILD
  report/producer/ReportProducer.java
Labels: bug, refactor

#326 Add tags to java library in lib/BUILD
  lib/BUILD
Labels: build, refactor

#327 Adapt to delete queries returning Void
  report/producer/AnswerAnalysis.java
  report/producer/QueriesExecutor.java
Labels: bug, build
