Repository graknlabs/benchmark, pull requests merged in 2019-01, with the labels that each got.

#90 Benchmark runner distribution
  BUILD
  WORKSPACE
  runner/BUILD
  runner/runner.sh
Labels: build, v1.5

#89 Metric preserving data generator
  metric/AllMetrics.java
  metric/Assortativity.java
  metric/BUILD
  metric/GlobalTransitivity.java
  metric/GraknGraphProperties.java
  metric/GraphProperties.java
  metric/StandardGraphProperties.java
  runner/conf/societal_model/societal_config_1.yml
  runner/conf/web_content/web_content_config.yml
  runner/src/BenchmarkRunner.java
  runner/src/generator/AttributeGenerator.java
  runner/src/generator/DataGenerator.java
  runner/src/generator/EntityGenerator.java
  runner/src/generator/RelationshipGenerator.java
  runner/src/pdf/DiscreteGaussianPDF.java
  runner/src/pick/CentralStreamProvider.java
  runner/src/pick/ConceptIdPicker.java
  runner/src/pick/StreamProvider.java
  runner/src/pick/StreamProviderInterface.java
  runner/src/probdensity/FixedBoundedZipf.java
  runner/src/probdensity/FixedConstant.java
  runner/src/probdensity/FixedDiscreteGaussian.java
  runner/src/probdensity/FixedUniform.java
  runner/src/probdensity/ProbabilityDensityFunction.java
  runner/src/probdensity/ScalingBoundedZipf.java
  runner/src/probdensity/ScalingConstant.java
  runner/src/probdensity/ScalingDiscreteGaussian.java
  runner/src/probdensity/ScalingUniform.java
  runner/src/schemaspecific/SchemaSpecificDataGenerator.java
  runner/src/schemaspecific/SchemaSpecificDataGeneratorFactory.java
  runner/src/schemaspecific/SocietalModelGenerator.java
  runner/src/schemaspecific/WebContentGenerator.java
  runner/src/specificstrategies/SpecificStrategyFactory.java
  runner/src/storage/ConceptStore.java
  runner/src/storage/ConceptTypeCountStore.java
  runner/src/storage/IgniteConceptIdStore.java
  runner/src/strategy/AttributeStrategy.java
  runner/src/strategy/EntityStrategy.java
  runner/src/strategy/GrowableGeneratedRouletteWheel.java
  runner/src/strategy/RelationshipStrategy.java
  runner/src/strategy/RolePlayerTypeStrategy.java
  runner/src/strategy/TypeStrategy.java
  runner/src/strategy/TypeStrategyInterface.java
  runner/test/storage/IgniteConceptIdStoreTest.java
Labels: feature, v1.5

#91 Zipf scale parameter bugfix
  runner/conf/web_content/queries.yml
  runner/conf/web_content/web_content_config.yml
  runner/conf/web_content/web_content_schema.gql
  runner/src/generator/DataGenerator.java
  runner/src/probdensity/ScalingBoundedZipf.java
  runner/src/schemaspecific/WebContentGenerator.java
  runner/src/storage/ConceptStore.java
  runner/src/storage/IgniteConceptIdStore.java
Labels: bug, v1.5

#97 Redefine Graph Scale in Data Generator
  runner/BUILD
  runner/conf/societal_model/societal_config_1.yml
  runner/conf/web_content/web_content_config.yml
  runner/src/BenchmarkRunner.java
  runner/src/executionconfig/BenchmarkConfiguration.java
  runner/src/executionconfig/BenchmarkConfigurationFile.java
  runner/src/generator/AttributeGenerator.java
  runner/src/generator/DataGenerator.java
  runner/src/schemaspecific/SchemaSpecificDataGenerator.java
  runner/src/schemaspecific/SocietalModelGenerator.java
  runner/src/schemaspecific/WebContentGenerator.java
  runner/src/storage/ConceptStore.java
  runner/src/storage/IgniteConceptIdStore.java
  runner/src/storage/InsertionAnalysis.java
  runner/test/storage/IgniteConceptIdStoreTest.java
  runner/test/storage/InsertionAnalysisTest.java
Labels: refactor, v1.6

#99 Fix failing `metric` tests
  metric/test/AssortativityIT.java
  metric/test/DegreeDistributionIT.java
  metric/test/GlobalTransitivityIT.java
  metric/test/GlobalTransitivityTest.java
Labels: bug, v1.6

#105 Track roles played in Ignite, data generator performance enhancement
  dependencies/maven/artifacts/com/google/guava/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  runner/BUILD
  runner/conf/web_content/web_content_config.yml
  runner/src/GraknBenchmark.java
  runner/src/exception/DataGeneratorException.java
  runner/src/generator/DataGenerator.java
  runner/src/pick/NotInRelationshipConceptIdStream.java
  runner/src/schemaspecific/WebContentGenerator.java
  runner/src/storage/ConceptStore.java
  runner/src/storage/IdStoreInterface.java
  runner/src/storage/IgniteConceptIdStore.java
  runner/src/storage/InsertionAnalysis.java
  runner/src/storage/NotInRelationshipConceptIdPicker.java
  runner/src/storage/SchemaManager.java
  runner/test-end-to-end/SchemaManagerE2E.java
  runner/test/storage/BUILD
  runner/test/storage/IgniteConceptIdStoreTest.java
  runner/test/storage/InsertionAnalysisTest.java
Labels: bug, refactor, v1.6

#106 Add pre-insert SQL existance check
  runner/src/storage/IgniteConceptIdStore.java
Labels: feature, v1.6

#107 Add --elastic-uri parameter to GraknBenchmark
  runner/conf/societal_model/societal_config_1.yml
  runner/conf/web_content/web_content_config.yml
  runner/src/GraknBenchmark.java
  runner/src/util/BenchmarkArguments.java
  runner/src/util/BenchmarkConfiguration.java
  runner/src/util/ElasticSearchManager.java
  runner/test-end-to-end/BUILD
  runner/test-end-to-end/SchemaManagerE2E.java
  runner/test/BUILD
  runner/test/GraknBenchmarkTest.java
Labels: feature, v1.6

#109 Create attributes identically to Entities and Relationships in Data Generator
  runner/conf/web_content/web_content_config.yml
  runner/src/generator/AttributeGenerator.java
  runner/src/generator/DataGenerator.java
  runner/src/generator/RelationshipGenerator.java
  runner/src/pick/StringStreamGenerator.java
  runner/src/schemaspecific/SocietalModelGenerator.java
  runner/src/schemaspecific/WebContentGenerator.java
  runner/src/storage/IgniteConceptIdStore.java
  runner/src/strategy/AttributeOwnerTypeStrategy.java
  runner/src/strategy/AttributeStrategy.java
  runner/src/strategy/GrowableGeneratedRouletteWheel.java
  runner/test/storage/IgniteConceptIdStoreTest.java
Labels: refactor

#117 Update zipkin tracing tags and ordering
  README.md
  dashboard/ZipkinESStorage.py
  dashboard/dashboard.py
  runner/conf/societal_model/societal_config_1.yml
  runner/conf/web_content/web_content_config.yml
  runner/setup.sh
  runner/src/GraknBenchmark.java
  runner/src/executor/QueryProfiler.java
  runner/src/generator/DataGenerator.java
  runner/src/util/BenchmarkArguments.java
  runner/src/util/BenchmarkConfiguration.java
  runner/src/util/BenchmarkConfigurationFile.java
  runner/test/GraknBenchmarkTest.java
  runner/test/resources/web_content/web_content_config_test.yml
Labels: refactor

#120 New Benchmark Graphs - Social Network and Road Network (1/2)
  BUILD
  runner/conf/biochem_network/biochem_config.yml
  runner/conf/biochem_network/biological_network.gql
  runner/conf/biochem_network/queries.yml
  runner/conf/financial_transactions/financial.gql
  runner/conf/financial_transactions/financial_config.yml
  runner/conf/financial_transactions/queries.yml
  runner/conf/road_network/queries.yml
  runner/conf/road_network/road_config.yml
  runner/conf/road_network/road_network.gql
  runner/conf/social_network/queries.yml
  runner/conf/social_network/social_network.gql
  runner/conf/social_network/social_network_config.yml
  runner/src/GraknBenchmark.java
  runner/src/generator/DataGenerator.java
  runner/src/pick/CentralStreamProvider.java
  runner/src/schemaspecific/RoadNetworkGenerator.java
  runner/src/schemaspecific/SchemaSpecificDataGeneratorFactory.java
  runner/src/schemaspecific/SocialNetworkGenerator.java
  runner/src/schemaspecific/SocietalModelGenerator.java
  runner/src/schemaspecific/WebContentGenerator.java
  runner/src/storage/IgniteConceptIdStore.java
  runner/src/storage/SchemaManager.java
  runner/test/pick/BUILD
  runner/test/pick/CentralStreamProviderTest.java
  runner/test/storage/IgniteConceptIdStoreTest.java
Labels: feature

#121 Refactor metrics and scale accounting in Data Generator
  runner/conf/road_network/road_config.yml
  runner/conf/social_network/social_network_config.yml
  runner/src/GraknBenchmark.java
  runner/src/executor/QueryProfiler.java
  runner/src/generator/DataGenerator.java
  runner/src/schemaspecific/SchemaSpecificDataGenerator.java
  runner/src/storage/ConceptStore.java
  runner/src/storage/IgniteConceptIdStore.java
  runner/test/storage/IgniteConceptIdStoreTest.java
Labels: refactor
